{"links": {"self": {"href": "data/repositories/hoffmanlab/segtools/issues/28/comments/16831356.json"}, "html": {"href": "#!/hoffmanlab/segtools/issues/28#comment-16831356"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/segtools/issues/28.json"}}, "type": "issue", "id": 28, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segtools.json"}, "html": {"href": "#!/hoffmanlab/segtools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{981b7f63-4900-4255-97c0-c244f833a3ee}ts=python"}}, "type": "repository", "name": "segtools", "full_name": "hoffmanlab/segtools", "uuid": "{981b7f63-4900-4255-97c0-c244f833a3ee}"}, "title": "segtools-aggregation fails in gene mode when annotation is preprocessed"}, "content": {"raw": "Comment [#2](https://code.google.com/p/segtools/issues/detail?id=28#c2) originally posted by ericr86 on 2012-07-10T21:52:02.000Z:\n\nI forgot the stack trace:\r\n\r\nLoading GeneAnnotation from file: data/5-paper_aggregation/gencode/gencode.v7.annotation.gtf.pkl.gz\r\n  Unpickling GeneAnnotation\r\nTraceback (most recent call last):\r\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/bin/segtools-aggregation\", line 8, in <module>\r\n    load_entry_point('segtools==1.1.10.dev-r374', 'console_scripts', 'segtools-aggregation')()\r\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374-py2.7.egg/segtools/aggregation.py\", line 963, in main\r\n    validate(bedfilename, featurefilename, outdir, **kwargs)\r\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374-py2.7.egg/segtools/aggregation.py\", line 840, in validate\r\n    features = GeneAnnotation(featurefilename, verbose=verbose)\r\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374-py2.7.egg/segtools/__init__.py\", line 93, in __init__\r\n    self._load(filename, verbose=verbose)\r\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374-py2.7.egg/segtools/__init__.py\", line 117, in _load\r\n    self._from_pickle(filename, verbose=verbose)\r\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374-py2.7.egg/segtools/__init__.py\", line 174, in _from_pickle\r\n    raise self.UnpickleError(msg)\r\nsegtools.UnpickleError: Error: Cannot to load an indexed Annotation object as an indexed GeneAnnotation object.\r\n\r\nThis appears to occur due to an inheritance issue. GeneAnnotation is a subclass of Annotation. When a gene annotation is pickled it is pickled at a plain Annotation. On line 169 of __init__.py (inherited from Annotation by GeneAnnotation) GeneAnnotation is trying to load an Annotation as a GeneAnnotation, which will fail.\r\n", "markup": "creole", "html": "<p>Comment [<a href=\"#!/hoffmanlab/segtools/issues/2/file-processing-error-handling-should\" rel=\"nofollow\" title=\"File processing error handling should print line number\" class=\"ap-connect-link\">#2</a>](<a href=\"https://code.google.com/p/segtools/issues/detail?id=28#c2\" rel=\"nofollow\">https://code.google.com/p/segtools/issues/detail?id=28#c2</a>) originally posted by ericr86 on 2012-07-10T21:52:02.000Z:</p>\n<p>I forgot the stack trace:</p>\n<p>Loading GeneAnnotation from file: data/5-paper_aggregation/gencode/gencode.v7.annotation.gtf.pkl.gz\n  Unpickling GeneAnnotation\nTraceback (most recent call last):\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/bin/segtools-aggregation\", line 8, in &lt;module&gt;\n    load_entry_point('segtools==1.1.10.dev-r374', 'console_scripts', 'segtools-aggregation')()\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374<a href=\"http://-py2.7.egg/segtools/aggregation.py\" rel=\"nofollow\" class=\"ap-connect-link\">-py2.7.egg/segtools/aggregation.py</a>\", line 963, in main\n    validate(bedfilename, featurefilename, outdir, <strong>kwargs)\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374<a href=\"http://-py2.7.egg/segtools/aggregation.py\" rel=\"nofollow\" class=\"ap-connect-link\">-py2.7.egg/segtools/aggregation.py</a>\", line 840, in validate\n    features = GeneAnnotation(featurefilename, verbose=verbose)\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374<a href=\"http://-py2.7.egg/segtools/\" rel=\"nofollow\" class=\"ap-connect-link\">-py2.7.egg/segtools/</a><u>init</u>.py\", line 93, in <u>init</u>\n    self._load(filename, verbose=verbose)\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374<a href=\"http://-py2.7.egg/segtools/\" rel=\"nofollow\" class=\"ap-connect-link\">-py2.7.egg/segtools/</a><u>init</u>.py\", line 117, in _load\n    self._from_pickle(filename, verbose=verbose)\n  File \"/net/noble/vol1/home/epaul9/arch/Linux/RHEL5/x86_64/lib/python2.7/segtools-1.1.10.dev_r374<a href=\"http://-py2.7.egg/segtools/\" rel=\"nofollow\" class=\"ap-connect-link\">-py2.7.egg/segtools/</a><u>init</u>.py\", line 174, in _from_pickle\n    raise self.UnpickleError(msg)\nsegtools.UnpickleError: Error: Cannot to load an indexed Annotation object as an indexed GeneAnnotation object.</strong></p>\n<p>This appears to occur due to an inheritance issue. GeneAnnotation is a subclass of Annotation. When a gene annotation is pickled it is pickled at a plain Annotation. On line 169 of <u>init</u>.py (inherited from Annotation by GeneAnnotation) GeneAnnotation is trying to load an Annotation as a GeneAnnotation, which will fail.</p>\n", "type": "rendered"}, "created_on": "2012-07-10T21:52:02+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": "2012-07-10T21:52:02+00:00", "type": "issue_comment", "id": 16831356}