{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/hoffmanlab/segtools/issues/33/comments/16831362.json"}, "html": {"href": "#!/hoffmanlab/segtools/issues/33#comment-16831362"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/segtools/issues/33.json"}}, "type": "issue", "id": 33, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segtools.json"}, "html": {"href": "#!/hoffmanlab/segtools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{981b7f63-4900-4255-97c0-c244f833a3ee}ts=python"}}, "type": "repository", "name": "segtools", "full_name": "hoffmanlab/segtools", "uuid": "{981b7f63-4900-4255-97c0-c244f833a3ee}"}, "title": "problems after installing segtools"}, "content": {"raw": "Comment [#1](https://code.google.com/p/segtools/issues/detail?id=33#c1) originally posted by ericr86 on 2015-02-24T18:59:21.000Z:\n\nHello!\r\n\r\nWhat seems to be happening here is that the script is being run cannot resolve the package that you've clearly installed using the install.py script. There could be a number of reasons for this.\r\n\r\nYou can verify if python can find segtools by running \"pip list\" and check if \"segtools (1.1.9)\" is anywhere in the list. Alternatively you can simply run python from the command line then run \"import segtools\" to see if you get an import error.\r\n\r\nI suspect what happened is something went wrong between your environment and the install script. It looks like segtools installed to the directory /usr/local/lib/python2.7/dist-packages/lib/python2.7. Can you verify if this is on your python path? If you run:\r\n\r\npython -c \"import sys;print sys.path\"\r\n\r\nIt will print out all the directories where packages are looking. If it's not on your path you can simply add \"/usr/local/lib/python2.7/dist-packages/lib/python2.7\" to your path by adding it in to your existing $PYTHONPATH variable like so:\r\n\r\nset PYTHONPATH=\"/usr/local/lib/python2.7/dist-packages/lib/python2.7:${PYTHONPATH}\"\r\n\r\nHope that helps!", "markup": "markdown", "html": "<p>Comment <a data-is-external-link=\"true\" href=\"https://code.google.com/p/segtools/issues/detail?id=33#c1\" rel=\"nofollow\">#1</a> originally posted by ericr86 on 2015-02-24T18:59:21.000Z:</p>\n<p>Hello!</p>\n<p>What seems to be happening here is that the script is being run cannot resolve the package that you've clearly installed using the install.py script. There could be a number of reasons for this.</p>\n<p>You can verify if python can find segtools by running \"pip list\" and check if \"segtools (1.1.9)\" is anywhere in the list. Alternatively you can simply run python from the command line then run \"import segtools\" to see if you get an import error.</p>\n<p>I suspect what happened is something went wrong between your environment and the install script. It looks like segtools installed to the directory /usr/local/lib/python2.7/dist-packages/lib/python2.7. Can you verify if this is on your python path? If you run:</p>\n<p>python -c \"import sys;print sys.path\"</p>\n<p>It will print out all the directories where packages are looking. If it's not on your path you can simply add \"/usr/local/lib/python2.7/dist-packages/lib/python2.7\" to your path by adding it in to your existing $PYTHONPATH variable like so:</p>\n<p>set PYTHONPATH=\"/usr/local/lib/python2.7/dist-packages/lib/python2.7:${PYTHONPATH}\"</p>\n<p>Hope that helps!</p>", "type": "rendered"}, "created_on": "2015-02-24T18:59:21+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": "2015-02-24T18:59:21+00:00", "type": "issue_comment", "id": 16831362}], "page": 1, "size": 1}